// Auto-generated by scripts/sync-credly.mjs
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const USERNAME = "jhoan-rojas";
const URL = `https://www.credly.com/users/${USERNAME}/badges.json`;
const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "../src/data/certifications.ts");

function mapBadges(json) {
  const data = json?.data;
  if (!Array.isArray(data)) return [];

  return data
    .map((b) => {
      const template = b.badge_template ?? {};
      const name = typeof template.name === "string" ? template.name : "";
      const issuerEntities = template.issuer?.entities ?? [];
      let issuer = "";
      for (const e of issuerEntities) {
        const entity = e.entity ?? {};
        if (entity.type === "Organization") {
          issuer = typeof entity.name === "string" ? entity.name : "";
          break;
        }
      }
      let badgeImage = typeof template.image?.url === "string" ? template.image.url : "";
      const date = typeof b.issued_at_date === "string" ? b.issued_at_date.slice(0, 7) : "";
      const id = typeof b.id === "string" ? b.id : "";

      if (!name || !id || !badgeImage) return null;

      return {
        name,
        issuer,
        category: issuer,
        date,
        badgeImage,
        credentialUrl: `https://www.credly.com/badges/${id}`,
      };
    })
    .filter(Boolean)
    .sort((a, b) => b.date.localeCompare(a.date));
}

function serialize(badges) {
  const body = badges.map((b) => `  ${JSON.stringify(b)}`).join(",\n");
  return `export type Certification = {
  name: string;
  issuer: string;
  category: string;
  date: string;
  badgeImage: string;
  credentialUrl: string;
};

export const certifications: Certification[] = [
${body},
];
`;
}

let badges = [];
try {
  const response = await fetch(URL, { signal: AbortSignal.timeout(15000) });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const json = await response.json();
  badges = mapBadges(json);
} catch (error) {
  console.warn(`[sync-credly] no se pudo actualizar desde Credly: ${error.message}`);
  if (!existsSync(OUT)) {
    writeFileSync(OUT, serialize([]));
    console.warn("[sync-credly] generado archivo vacío porque no existía respaldo local.");
  } else {
    console.log(`[sync-credly] se conserva el respaldo local existente (${readFileSync(OUT, "utf8").match(/^\s\{/gm)?.length ?? 0} entradas).`);
  }
  process.exit(0);
}

writeFileSync(OUT, serialize(badges));
console.log(`[sync-credly] ${badges.length} certificaciones sincronizadas desde Credly -> ${OUT}`);